config_cls: MossTTSPipelineConfig
model_path: OpenMOSS-Team/MOSS-TTS-v1.5

stages:
  preprocessing:
    factory:
      device: cpu
      compute_dtype: bfloat16
      max_concurrency: 1

  tts_engine:
    engine:
      max_running_requests: 1
      mem_fraction_static: 0.70
      cuda_graph_max_bs: 1

  vocoder:
    factory:
      dtype: bfloat16
      max_batch_size: 1
      max_batch_wait_ms: 2
